# PostgreSQL Veritaban? Ayarlar?
spring.datasource.url=jdbc:postgresql://localhost:5432/anakronik
spring.datasource.username=postgres
spring.datasource.password=admin

# JPA/Hibernate Ayarlar?
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# JWT Ayarlar?
jwt.secret=***REMOVED***
jwt.expiration-ms=1000000000
jwt.refresh-token.expiration-ms=604800000

spring.jpa.open-in-view=false

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=basaranmelik1@gmail.com
spring.mail.password=***REMOVED***
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.frontend.login-url=http://localhost:5173/login

# Yüklenecek resim dosyalar? için kal?c? dizin
app.figure.image-dir=./uploads/images/
